const axios = require('axios');
const { cmd } = require('../command');
const config = require("../config");
const { setConfig, getConfig } = require("../lib/configdb");
const fs = require('fs');
const path = require('path');
const { downloadTempMedia, cleanupTemp } = require("../lib/media-utils");

const simulateTyping = async (conn, jid, ms = 2000) => {
  await conn.sendPresenceUpdate('composing', jid);
  await new Promise(resolve => setTimeout(resolve, ms));
  await conn.sendPresenceUpdate('paused', jid);
};

let AI_STATE = {
  IB: "false",
  GC: "false"
};

cmd({
  pattern: "chatbot",
  alias: ["xylo"],
  desc: "Enable or disable AI chatbot responses",
  category: "ai",
  filename: __filename,
  react: "🤖"
}, async (conn, mek, m, { from, args, isOwner, reply }) => {
  if (!isOwner) return reply("❌ Only the bot owner can use this command.");

  const mode = args[0]?.toLowerCase();
  const target = args[1]?.toLowerCase();

  if (mode === "on") {
    if (!target || target === "all") {
      AI_STATE.IB = "true";
      AI_STATE.GC = "true";
    } else if (target === "pm") {
      AI_STATE.IB = "true";
    } else if (target === "gc") {
      AI_STATE.GC = "true";
    }
    await setConfig("AI_STATE", JSON.stringify(AI_STATE));
    return reply("✅ Xylo AI enabled for " + (target || "all") + " chats.");
  } else if (mode === "off") {
    if (!target || target === "all") {
      AI_STATE.IB = "false";
      AI_STATE.GC = "false";
    } else if (target === "pm") {
      AI_STATE.IB = "false";
    } else if (target === "gc") {
      AI_STATE.GC = "false";
    }
    await setConfig("AI_STATE", JSON.stringify(AI_STATE));
    return reply("❌ Xylo AI disabled for " + (target || "all") + " chats.");
  } else {
    return reply(`🤖 *Xylo AI Control Panel*

📥 PM: ${AI_STATE.IB === "true" ? "✅ On" : "❌ Off"}
👥 Group: ${AI_STATE.GC === "true" ? "✅ On" : "❌ Off"}

Usage:
${config.PREFIX}chatbot on|off all|pm|gc`);
  }
});

(async () => {
  const saved = await getConfig("AI_STATE");
  if (saved) AI_STATE = JSON.parse(saved);
})();

cmd({
  on: "body"
}, async (conn, m, store, {
  from,
  body,
  isGroup,
  sender,
  reply
}) => {
  try {
    if (m.key.fromMe || body?.startsWith(config.PREFIX)) return;

    const allowed = isGroup ? AI_STATE.GC === "true" : AI_STATE.IB === "true";
    if (!allowed) return;

    const quoted = m?.message?.extendedTextMessage?.contextInfo?.participant;
    const botJid = conn.user.id.split(':')[0] + '@s.whatsapp.net';
    const mentionedBot = body?.toLowerCase().includes("say it") || quoted === botJid;

    if (!mentionedBot && !m?.message?.audioMessage) return;

    const isAudio = !!m.message.audioMessage;
    let promptText = body;

    // 🧠 Audio Transcription (currently skipped because Whisper is down)
    if (isAudio) {
      const audioBuffer = await conn.downloadAndSaveMediaMessage(m, "./tmp/voice.ogg");
      promptText = "Hello"; // default fallback
      fs.unlinkSync(audioBuffer);
    }

    // 🖼️ Image Generation
    if (body.toLowerCase().startsWith("draw ")) {
      const prompt = body.slice(5).trim();
      const { data: draw } = await axios.post('https://xylo-ai.onrender.com/draw', {
        prompt
      });
      const imgPath = await downloadTempMedia(draw.imageUrl, 'xylo_img.jpg');
      await conn.sendMessage(from, { image: fs.readFileSync(imgPath), caption: "🖼️ Generated by 𝕏ʏʟᴏ" }, { quoted: m });
      cleanupTemp(imgPath);
      return;
    }

    // ⌨️ Simulate Typing
    const duration = Math.floor(Math.random() * 1500) + 1500;
    await simulateTyping(conn, from, duration);

    // 🤖 AI Chat Response
    const { data } = await axios.post('https://xylo-ai.onrender.com/ask', {
      userId: sender,
      message: promptText
    });

    if (data?.reply) {
      await conn.sendMessage(from, { text: data.reply, ai: true }, { quoted: m });

      // 🔊 Voice Reply
      if (isAudio || body.toLowerCase().includes("say it")) {
        const { data: voiceRes } = await axios.post('https://xylo-ai.onrender.com/voice', {
          text: data.reply
        });

        const tempPath = path.join(__dirname, '../tmp/xylo_voice.mp3');
        const writer = fs.createWriteStream(tempPath);
        const audioRes = await axios.get(voiceRes.audioUrl, { responseType: "stream" });

        audioRes.data.pipe(writer);
        await new Promise((resolve, reject) => {
          writer.on("finish", resolve);
          writer.on("error", reject);
        });

        await conn.sendMessage(from, {
          audio: fs.readFileSync(tempPath),
          mimetype: 'audio/mp4',
          ptt: true
        }, { quoted: m });

        fs.unlinkSync(tempPath);
      }
    } else {
      reply("⚠️ No reply from Xylo.");
    }
  } catch (err) {
    console.error("AI Chat Error:", err.message);
    reply("⚠️ Xylo AI error occurred.");
  }
});
